
name: ci
on:
  push:
  schedule: # At 03:47
    - cron: '47 3 * * *'

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Install package & test
        run: make
