
name: ci
on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Install package & test
        run: make
